spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestionstockapi?createDatabaseIfNotExist=true&userSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  ## Specify DBMS
  jpa:
    database: MYSQL
    show-sql: false
    # Hibernate DDL Auto (create, create-drop, update)
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: 8081


flickr:
  apiKey: d70c504bd0d3aab8e2c2411bac8edd64
  apiSecret: b8306a3c9c443be0
  appKey: 72157720913967034-f00dab211a4be0ce
  appSecret: 5b1276c9269321ca
